# --- Basic options --- #

# Name of website
title: Easy Cocoa

# Short description of your site
description: I love programming

# Your name to show in the footer
author: Hojun Rooney Baek

# --- List of links in the navigation bar --- #

navbar-links:
  Home: "/"
  About Me: "pages/about"
  Books: "pages/books"
  Portfolio: "pages/portfolio"
  Projects:
    - Account Password Manager: "pages/account-password-manager"
    - Instagallry: "pages/instagallry"
    - Health Tutorial: "pages/healthtutorial"

#  Resources:
#    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
#    - Learn markdown: "http://www.markdowntutorial.com/"
#  Author's home: "http://deanattali.com"

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/avatar-icon.jpg"

# By default, the image is cut into a circle. You can disable this behaviour here.
round-avatar: true

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
#title-img: /path/to/image


# --- Footer options --- #

# Change all these values or delete the ones you don't want.

# Select your active Social Network Links.
# Uncomment the links you want to show in the footer and add your information to each link.
# You can reorder the items to define the link order.
# If you want to add a new link that isn't here, you'll need to also edit the file _data/SocialNetworks.yml
social-network-links:
  rss: true
  email: "mr.hjbaek@gmail.com"
  facebook: hojun.baek
  github: hjbaek
  twitter: ezcocoa
#  reddit: yourname
  linkedin: hojunbaek
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  youtube: user/deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname
#  telegram: yourname
#  calendly: yourname

# --- General options --- #

# Select which social network share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: true

# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "ezcocoa.com"  # eg. "deanattali.com/beautiful-jekyll"
link-tags: true

# Excerpt Word Length - Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50
navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-border-col: "#EAEAEA"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"

# --- Web Statistics Section --- #

# Fill in your Google Analytics gtag.js ID to track your website using gtag
#gtag: ""

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: ""

# Google Tag Manager ID
#gtm: ""

# Matomo (aka Piwik) Web statistics
# Uncomment the following section to enable Matomo. The opt-out parameter controls
# whether or not you want to allow users to opt out of tracking.
#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

# --- Comments --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: "ezcocoa"

# If you want to use JustComments fill with the API Key
#just-comments: "ABCD-EFGH-IJKL"

# To use Facebook Comments, fill in a Facebook App ID
# fb_comment_id: ""

# To use Staticman comments, fill in repository, branch, and endpoint
# staticman:
#   repository : # GitHub username/repository eg. "daattali/beautiful-jekyll"
#   branch     : master # If you're not using `master` branch, then you also need to update the `branch` parameter in `staticman.yml`
#   endpoint   : # URL of your own deployment, with a trailing slash (will fallback to a public GitLab instance) eg. https://<your-api>/v3/entry/github/
#   reCaptcha:
#     # reCaptcha for Staticman (OPTIONAL, but recommended for spam protection)
#     # If you use reCaptcha, you must also set these parameters in staticman.yml
#     siteKey  : # Use your own site key, you need to apply for one on Google
#     secret   : # ENCRYPT your password by going to https://staticman3.herokuapp.com/v3/encrypt/<your-site-secret>

# --- Misc --- #

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"


# --- You don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Asia/Seoul"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
      readtime: false # add estimated reading time on all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: false

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
